//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WS_gen12.camiones_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Camiones_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Camiones_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_CamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_CamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        private int CapacidadField;
        
        private double KilometrajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlFotoField;
        
        private bool DisponibilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Camion {
            get {
                return this.ID_CamionField;
            }
            set {
                if ((this.ID_CamionField.Equals(value) != true)) {
                    this.ID_CamionField = value;
                    this.RaisePropertyChanged("ID_Camion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo_Camion {
            get {
                return this.Tipo_CamionField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_CamionField, value) != true)) {
                    this.Tipo_CamionField = value;
                    this.RaisePropertyChanged("Tipo_Camion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Capacidad {
            get {
                return this.CapacidadField;
            }
            set {
                if ((this.CapacidadField.Equals(value) != true)) {
                    this.CapacidadField = value;
                    this.RaisePropertyChanged("Capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Kilometraje {
            get {
                return this.KilometrajeField;
            }
            set {
                if ((this.KilometrajeField.Equals(value) != true)) {
                    this.KilometrajeField = value;
                    this.RaisePropertyChanged("Kilometraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UrlFoto {
            get {
                return this.UrlFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlFotoField, value) != true)) {
                    this.UrlFotoField = value;
                    this.RaisePropertyChanged("UrlFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Disponibilidad {
            get {
                return this.DisponibilidadField;
            }
            set {
                if ((this.DisponibilidadField.Equals(value) != true)) {
                    this.DisponibilidadField = value;
                    this.RaisePropertyChanged("Disponibilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="camiones_Service.camiones_ServiceSoap")]
    public interface camiones_ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento camion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_Camion", ReplyAction="*")]
        Cliente_WS_gen12.camiones_Service.insertar_CamionResponse insertar_Camion(Cliente_WS_gen12.camiones_Service.insertar_CamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_Camion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.insertar_CamionResponse> insertar_CamionAsync(Cliente_WS_gen12.camiones_Service.insertar_CamionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Camiones", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS_gen12.camiones_Service.Camiones_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS_gen12.camiones_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS_gen12.camiones_Service.Camiones_VO[]))]
        Cliente_WS_gen12.camiones_Service.Get_CamionesResponse Get_Camiones(Cliente_WS_gen12.camiones_Service.Get_CamionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Camiones", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.Get_CamionesResponse> Get_CamionesAsync(Cliente_WS_gen12.camiones_Service.Get_CamionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento camion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_Camion", ReplyAction="*")]
        Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse actualizar_Camion(Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_Camion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse> actualizar_CamionAsync(Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminar_CamionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_Camion", ReplyAction="*")]
        Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse eliminar_Camion(Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_Camion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse> eliminar_CamionAsync(Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertar_CamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertar_Camion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.insertar_CamionRequestBody Body;
        
        public insertar_CamionRequest() {
        }
        
        public insertar_CamionRequest(Cliente_WS_gen12.camiones_Service.insertar_CamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertar_CamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS_gen12.camiones_Service.Camiones_VO camion;
        
        public insertar_CamionRequestBody() {
        }
        
        public insertar_CamionRequestBody(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            this.camion = camion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertar_CamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertar_CamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.insertar_CamionResponseBody Body;
        
        public insertar_CamionResponse() {
        }
        
        public insertar_CamionResponse(Cliente_WS_gen12.camiones_Service.insertar_CamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertar_CamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertar_CamionResult;
        
        public insertar_CamionResponseBody() {
        }
        
        public insertar_CamionResponseBody(string insertar_CamionResult) {
            this.insertar_CamionResult = insertar_CamionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CamionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Camiones", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.Get_CamionesRequestBody Body;
        
        public Get_CamionesRequest() {
        }
        
        public Get_CamionesRequest(Cliente_WS_gen12.camiones_Service.Get_CamionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_CamionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS_gen12.camiones_Service.ArrayOfAnyType parametros;
        
        public Get_CamionesRequestBody() {
        }
        
        public Get_CamionesRequestBody(Cliente_WS_gen12.camiones_Service.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CamionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_CamionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.Get_CamionesResponseBody Body;
        
        public Get_CamionesResponse() {
        }
        
        public Get_CamionesResponse(Cliente_WS_gen12.camiones_Service.Get_CamionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_CamionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS_gen12.camiones_Service.Camiones_VO[] Get_CamionesResult;
        
        public Get_CamionesResponseBody() {
        }
        
        public Get_CamionesResponseBody(Cliente_WS_gen12.camiones_Service.Camiones_VO[] Get_CamionesResult) {
            this.Get_CamionesResult = Get_CamionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizar_CamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizar_Camion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.actualizar_CamionRequestBody Body;
        
        public actualizar_CamionRequest() {
        }
        
        public actualizar_CamionRequest(Cliente_WS_gen12.camiones_Service.actualizar_CamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizar_CamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS_gen12.camiones_Service.Camiones_VO camion;
        
        public actualizar_CamionRequestBody() {
        }
        
        public actualizar_CamionRequestBody(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            this.camion = camion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizar_CamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizar_CamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.actualizar_CamionResponseBody Body;
        
        public actualizar_CamionResponse() {
        }
        
        public actualizar_CamionResponse(Cliente_WS_gen12.camiones_Service.actualizar_CamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizar_CamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string actualizar_CamionResult;
        
        public actualizar_CamionResponseBody() {
        }
        
        public actualizar_CamionResponseBody(string actualizar_CamionResult) {
            this.actualizar_CamionResult = actualizar_CamionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminar_CamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminar_Camion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.eliminar_CamionRequestBody Body;
        
        public eliminar_CamionRequest() {
        }
        
        public eliminar_CamionRequest(Cliente_WS_gen12.camiones_Service.eliminar_CamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminar_CamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public eliminar_CamionRequestBody() {
        }
        
        public eliminar_CamionRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminar_CamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminar_CamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_gen12.camiones_Service.eliminar_CamionResponseBody Body;
        
        public eliminar_CamionResponse() {
        }
        
        public eliminar_CamionResponse(Cliente_WS_gen12.camiones_Service.eliminar_CamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminar_CamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminar_CamionResult;
        
        public eliminar_CamionResponseBody() {
        }
        
        public eliminar_CamionResponseBody(string eliminar_CamionResult) {
            this.eliminar_CamionResult = eliminar_CamionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface camiones_ServiceSoapChannel : Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class camiones_ServiceSoapClient : System.ServiceModel.ClientBase<Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap>, Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap {
        
        public camiones_ServiceSoapClient() {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public camiones_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS_gen12.camiones_Service.insertar_CamionResponse Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.insertar_Camion(Cliente_WS_gen12.camiones_Service.insertar_CamionRequest request) {
            return base.Channel.insertar_Camion(request);
        }
        
        public string insertar_Camion(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            Cliente_WS_gen12.camiones_Service.insertar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.insertar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.insertar_CamionRequestBody();
            inValue.Body.camion = camion;
            Cliente_WS_gen12.camiones_Service.insertar_CamionResponse retVal = ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).insertar_Camion(inValue);
            return retVal.Body.insertar_CamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.insertar_CamionResponse> Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.insertar_CamionAsync(Cliente_WS_gen12.camiones_Service.insertar_CamionRequest request) {
            return base.Channel.insertar_CamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.insertar_CamionResponse> insertar_CamionAsync(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            Cliente_WS_gen12.camiones_Service.insertar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.insertar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.insertar_CamionRequestBody();
            inValue.Body.camion = camion;
            return ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).insertar_CamionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS_gen12.camiones_Service.Get_CamionesResponse Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.Get_Camiones(Cliente_WS_gen12.camiones_Service.Get_CamionesRequest request) {
            return base.Channel.Get_Camiones(request);
        }
        
        public Cliente_WS_gen12.camiones_Service.Camiones_VO[] Get_Camiones(Cliente_WS_gen12.camiones_Service.ArrayOfAnyType parametros) {
            Cliente_WS_gen12.camiones_Service.Get_CamionesRequest inValue = new Cliente_WS_gen12.camiones_Service.Get_CamionesRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.Get_CamionesRequestBody();
            inValue.Body.parametros = parametros;
            Cliente_WS_gen12.camiones_Service.Get_CamionesResponse retVal = ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).Get_Camiones(inValue);
            return retVal.Body.Get_CamionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.Get_CamionesResponse> Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.Get_CamionesAsync(Cliente_WS_gen12.camiones_Service.Get_CamionesRequest request) {
            return base.Channel.Get_CamionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.Get_CamionesResponse> Get_CamionesAsync(Cliente_WS_gen12.camiones_Service.ArrayOfAnyType parametros) {
            Cliente_WS_gen12.camiones_Service.Get_CamionesRequest inValue = new Cliente_WS_gen12.camiones_Service.Get_CamionesRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.Get_CamionesRequestBody();
            inValue.Body.parametros = parametros;
            return ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).Get_CamionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.actualizar_Camion(Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest request) {
            return base.Channel.actualizar_Camion(request);
        }
        
        public string actualizar_Camion(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.actualizar_CamionRequestBody();
            inValue.Body.camion = camion;
            Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse retVal = ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).actualizar_Camion(inValue);
            return retVal.Body.actualizar_CamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse> Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.actualizar_CamionAsync(Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest request) {
            return base.Channel.actualizar_CamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.actualizar_CamionResponse> actualizar_CamionAsync(Cliente_WS_gen12.camiones_Service.Camiones_VO camion) {
            Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.actualizar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.actualizar_CamionRequestBody();
            inValue.Body.camion = camion;
            return ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).actualizar_CamionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.eliminar_Camion(Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest request) {
            return base.Channel.eliminar_Camion(request);
        }
        
        public string eliminar_Camion(int id) {
            Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.eliminar_CamionRequestBody();
            inValue.Body.id = id;
            Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse retVal = ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).eliminar_Camion(inValue);
            return retVal.Body.eliminar_CamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse> Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap.eliminar_CamionAsync(Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest request) {
            return base.Channel.eliminar_CamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS_gen12.camiones_Service.eliminar_CamionResponse> eliminar_CamionAsync(int id) {
            Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest inValue = new Cliente_WS_gen12.camiones_Service.eliminar_CamionRequest();
            inValue.Body = new Cliente_WS_gen12.camiones_Service.eliminar_CamionRequestBody();
            inValue.Body.id = id;
            return ((Cliente_WS_gen12.camiones_Service.camiones_ServiceSoap)(this)).eliminar_CamionAsync(inValue);
        }
    }
}
